baseURL = "/about"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "That Data Person"
[menu]
main = []
[params]
address = "First Floor Telecom House, 125 - 135 Preston Road, Brighton, England, BN1 6AF"
author = "That Data Person Limited"
copyright = "Copyright 2022"
description = "That Data Person Limited"
email = "hello@thatdataperson.com"
google_analitycs_id = "Your ID"
home = "About"
logo = ""
phone = "+44 7874 374184"
theme_color = "#4320cc"
[params.contact]
enable = false
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.facebook.com/thatdataperson"
icon = "ti-facebook"
[[params.social]]
URL = "https://twitter.com/thatdataperson"
icon = "ti-twitter-alt"
